services:
  steam-app:
    image: ghcr.io/riptir3/steampricecheckerconsoleapp:latest
    container_name: steam-app
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44 
    command: --interval 60 --cleanup steam-app