name: Docker and EXE Build

on:
  push:
    branches: [ "main", "master" ] 
    tags:
      - 'v*'
  workflow_dispatch:     

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./SteamPriceCheckerConsoleApp 
          file: ./SteamPriceCheckerConsoleApp/Dockerfile
          push: true
          tags: ghcr.io/riptir3/steampricecheckerconsoleapp:latest   

  build-exe:
    runs-on: windows-latest
    permissions:
      contents: write 
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish EXE
        shell: pwsh
        run: |
          # Ha tag-ről van szó (v1.4.0), levágjuk a 'v' betűt. Ha csak push, akkor 0.0.1
          $RAW_VERSION = "${{ github.ref_name }}"
          $CLEAN_VERSION = if ("${{ github.ref_type }}" -eq "tag") { $RAW_VERSION.TrimStart('v') } else { "0.0.1" }
          
          dotnet publish ./SteamPriceCheckerConsoleApp/SteamPriceCheckerConsoleApp.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:Version=$CLEAN_VERSION `
            -o ./publish

      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish_output/SteamPriceCheckerConsoleApp.exe
          # Ezt írd át: Ne 'latest', hanem a Push-olt Tag neve legyen
          tag_name: ${{ github.ref_name }} 
          name: "Verzió ${{ github.ref_name }}"
          body: "Automatikusan generált frissítés a(z) ${{ github.ref_name }} verzióhoz."
          draft: false
          prerelease: false
          # Ez a sor fontos: ha már létezik a Tag, írja felül a fájlt
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
